org.gradle.jvmargs  = -Xmx3G
org.gradle.parallel = true
org.gradle.caching  = true

minecraft           = 26.1-rc-3

archiveBaseName     = wthit
group               = mcp.mobius.waila
majorVersion        = 19

# [rei, jei, emi]
recipeViewer        = none

badpackets          = 0.12.1
rei                 = 13.0.666
jei                 = 1.20.2-16.0.0.28
emi                 = 1.0.23+1.20.2

fabricLoader        = 0.18.4
fabricApi           = 0.144.0+26.1
modMenu             = 18.0.0-alpha.6
trEnergy            = 5.0.0

forge               = 61.0.2
neo                 = 26.1.0.1-beta

architectury        = 10.0.7
clothConfig         = 12.0.107

quiltLoader         = 0.24.0
qsl                 = 8.0.0-alpha.12+1.20.4
qfapi               = 9.0.0-alpha.7+0.96.11-1.20.4

spigotApi           = 1.18.2-R0.1-SNAPSHOT
paperclip           = 1.18.2-313
