#!/usr/bin/env bash

script_dir=$(dirname "$0")

# Create a symlink to common source on platform impl
ln -s "${script_dir}/common/src/main" "${script_dir}/fabric/src/common"
ln -s "${script_dir}/common/src/main" "${script_dir}/forge/src/common"
